services:
  app:
    build: 
      context: .
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_HOST=db:5432
    networks:
      - app-network
      
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge